### ISSUE TITLE
Is it possible to adjust for kinship?

### ISSUE THREAD

**Issue by complexgenome** [kbroman/lmmlite#2]
Can the library allow to adjust for kinship matrix?

**Comment by kbroman** [comment]
The point of the package is to fit a linear mixed model to account for kinship; see the [user guide](https://kbroman.org/lmmlite/assets/lmmlite.html). But this was really just a prototype, and I wouldn't recommend it for general use.

**Comment by complexgenome** [comment]
I'm confused. Is the library good enough for complex model or work in progress?

**Comment by kbroman** [comment]
You can do whatever you want with it, but as it says in the [README file](https://github.com/kbroman/lmmlite/blob/master/README.md), 

> In order to better understand pylmm, for linear mixed models for genome-wide association studies (GWAS), I wrote an R version of the algorithm.

There won't be any further work on the package.
